Eyepea/aiosip

- aiosip/dialog.py
- aiosip/message.py
When, for example, trying to close an inbound call, the To and From headers need to be flipped and different Contact/Via/request headers need to be provided.
Easiest way to offer that right now is to just allow those fields to be overridden.
> Allow overriding to, from and contact information on all messages

- aiosip/dialog.py
It is a very small change, but it is needed if a proxy authenticates a call. Since a lot of the information is repeated between www-authenticate and proxy-authenticate, there is likely a better way to add this.
> Added Proxy Authentication

- aiosip/call.py
Been a while since I've had the freetime to work on aiosip.
Small change - put the BYE message inside the call's future. This allows me to inspect why a call was hungup on me:
~~~python
def report_call(future):
result = future.result()
if not done_originating and result:
reason = result.headers['X-Asterisk-Hangupcause']
print('Call hung up early: {}'.format(reason))
future = asyncio.Future()
future.add_done_callback(report_call)
call = await Call.invite(dialog, ..., future=future)
~~~
> Put the BYE message in the call's future

- aiosip/dialog.py
Sorry for my quietness, I've been increadibly slammed with other QA tasks and haven't had a chance to look at any of this stuff for months. Finally got some freed up time to focus on this library again.
Tweaked `recieve_message` to handle other challenge response messages. Tested it with SUBSCRIBE, which now works.
> Always set a username for challenge response messages

- aiosip/application.py
- aiosip/dialog.py
- examples/subscribe_client.py
- examples/subscribe_server.py
Initial work to start encapsulating individual transactions. While currently it just moved the current transaction tracking logic out of the Dialog class, it opens the door to handling different kinds of transactions without messy branching logic, tracking state (setting up a callback to know when 180 arrived, for example), and properly supporting cancelling (send an appropriate CANCEL message).
Also fills in the server/client subscription example so that it actually sends arbitrary messages back and forth.
Next step is filling in some more transaction support to get a nicer API for the server side - support something in line with aiohttp's websocket support to handle incoming dialogs, map exceptions to error codes, and wrap responses for nice server code.
> Initial transaction tracking support.

- aiosip/pytest_plugin.py
- aiosip/transaction.py
- tests/conftest.py
- tests/test_sip_server.py
So the tests don't work yet, and I think I've found a few bugs already with this test (I have some typos in my earlier PR... 😰). But I think they're in good enough shape that they can be shared for review and merged in their current state. I'll finish them up tomorrow and integrate Travis as a I think I should be able to do that with my current permissions.
I borrowed ideas from aiohttp to enable both unit testing and a pytest plugin for others to test their own code with. Then port part of the subscribe server/client example a test to make sure it continues to work.
I also want to make sure uvloop has first class support as much as possible. My rough benchmarks when I first used uvloop + aiosip showed very promising performance.
> Add pytest support and a basic server/client test

- .travis.yml
- codecov.yml
- setup.cfg
- setup.py
- tox.ini
Adds travis and codecov integration. Works and tested on the sangoma/aiosip repository, but I don't have permissions to add it here. Should be a matter of just turning everything on.
Once this is in, I'll add the badges to the README.
> Add travis integration

- aiosip/pytest_plugin.py
I copy and pasted the tokio support for aiohttp testing into here, but didn't completely strip it out. This adds it back in - though it doesn't work yet, and honestly don't see the harm in it.
Otherwise I'll strip it out in full.
> Add tokio support, though it doesn't work yet.

- aiosip/connections.py
- aiosip/dialog.py
- aiosip/pytest_plugin.py
- tests/conftest.py
- tests/test_contact_parsing.py
- tests/test_sip_server.py
Makes sure we test both UDP and TCP over both the python event loop and uvloop. Had to add a few hacks to make sure we properly cleanup connections between tests in order to make sure the tests pass.
> Parameterize tests over UDP and TCP

- .travis.yml
- aiosip/application.py
- aiosip/dialog.py
- aiosip/dialplan.py
- aiosip/exceptions.py
- aiosip/message.py
- aiosip/peers.py
- aiosip/protocol.py
- aiosip/transaction.py
- examples/subscribe_client.py
- examples/subscribe_server.py
- tests/conftest.py
- tests/test_sip_proxy.py
- tests/test_sip_scenario.py
- tests/test_sip_server.py
- tox.ini
Lots of stuff moving around.
I believe it's best to use queues in transaction instead of a single `future` so we can pass the 100-200 status code response. It also allow better proxying of re-transmission. I'm not sure I did it the best way possible but it's a WIP.
At the moment it uses `async iterator` that are only available on 3.6. 
- Should we drop 3.5 ?
- It might be possible to do the same with `__aiter__` and `__anext__` ?
- Any ideas ?
> Queues in transaction

- aiosip/dialog.py
Fixes an issue where notify message with extra headers, when sent in a
loop, ends up with a pinned CSeq number.
Since the header structure is filled in before serializing and sending
on the wire - and not copied - we end up filling in the data structure
provided in the `header` named parameter.
This effectively leaks and shares state between distinct transactions.
> Always copy provided headers

- aiosip/application.py
- aiosip/peers.py
- aiosip/utils.py
This allow to run multiple endpoints and find the right peer
when they don't switch outgoing port
We can't use (peer_addr, local_addr) as key in the self._peers
dict as the local_addr is only know when the connection is
establisehd. It could lead to race condition when creating
connections to the same peer.
> Keep track of local addr for peer

- aiosip/contrib.py
- examples/subscribe_server.py
Putting this up because I would like to start working on some sort of API to make server implementation easier. I would like to eventually get to something like how aiohttp server side has a request object and then move this mechanism to something closer to how aiohttp handles websockets (this API obviously prevents you from rejecting traffic). I envision something like:
```python
async def my_subscription(request):
subscription = asyncio.Subscription()
await subscription.prepare(request)
for i in range(4):
subscription.send(i)
return subscription
```
But this PR gets me part of the way there.
> Introduce helper to track messages/requests that expire

- aiosip/peers.py
- examples/subscribe_client.py
The code which is supposed to close the transport was not being
called as the lookup on self._protocols was using the wrong key.
Also eliminate the "should_close" argument which is always True.
> Actually close protocol / transport

- aiosip/peers.py
This ensure the appropriate Sec-WebSocket-Protocol header is set.
Some browsers strictly enforce subprotocol selection and will close the
WebSocket if they do not receive the correct Sec-WebSocket-Protocol.
> [websockets] specify 'sip' subprotocol

- aiosip/application.py
- aiosip/peers.py
- aiosip/protocol.py
- examples/subscribe_client.py
- examples/subscribe_server.py
- tests/test_sip_proxy.py
- tests/test_sip_scenario.py
- tests/test_sip_server.py
The "_create_server" method returned something very different depending on whether the transport was UDP or TCP/WS. In the UDP case what was returned was in fact the protocol, which has neither "close" nor "await_closed()" methods.
These kind of differences should not be exposed outside the API boundary, as they mean special cases in our users' code.
Also, make app.close() the preferred way of shutting down the application.
> Make app.close() async, unify 'server' interface

- aiosip/peers.py
The transport specified in the Contact address should be lowercase
according to RFC 3261.
> [peers] lowercase transport in Contact address

- aiosip/contact.py
- tests/test_contact_parsing.py
- accept all tokens in unquoted name
- don't put whitespace into name
- correctly parse params when there is a space before params
Also:
- add tests for transforming the Contact back to a header string
- remove dead 'from_repr' code
> Improve Contact header parsing

- aiosip/dialog.py
- aiosip/dialplan.py
- tests/test_sip_scenario.py
- tests/test_sip_server.py
This API lets me work with a dialog without having to explicitly register a callback for every message.
It also means that there's no more implicit 404 handling either, but I'm not convinced you want to do that inside a dialog. I think that makes sense for the dialplan, but once a dialog is established, we probably want every incoming message to be explicitly handled, and with awareness of the order they arrived in.
Related to #65, but I'm going to close that and do it in two parts. If we get this in, I think it might make sense to look at removing or simplifying QueueTransaction API, and then proper INVITE support.
> Make dialog iterable instead of relying on a default handler

- aiosip/dialog.py
Initial commit of a debug flag. When set on a dialog, it will attach a traceback to 500 error messages.
Very provisional, flag doesn't propagate anywhere and needs to be set manually currently, but at the very least useful for debugging.
> Optionally add a traceback to 500 messages when debug flag set

- aiosip/application.py
- aiosip/peers.py
- examples/subscribe_client.py
Our subscribe example works, but it provides a From header with a port that doesn't match where the traffic actually came from.
Now since the Contact header is correct, its technically valid, but they really should match in this simple scenario (there's no proxy) and it really should be something specifiable.
> Should accept a local address when establishing a peer

- aiosip/application.py
- aiosip/dialog.py
- aiosip/dialplan.py
- aiosip/peers.py
- aiosip/transaction.py
- tests/test_sip_proxy.py
- tests/test_sip_scenario.py
- tests/test_sip_server.py
Putting this up for feedback. I know you guys have been kinda busy, so take your time, still a few things left to do:
The PR removes the dialog router. I plan to move everything to using an iterator based API.
In order to do this, I created a new Request class to represent a new potential dialog. This now fed to the callbacks registered in the dialplan, and give them room to either reject or accept traffic. Should it be accepted, a Dialog is returned.
This returned dialog object should now behave exactly like the client side dialog, meaning future messages on that dialog should be read out by iterating (enabling re-REGISTER support, for example).
This breaks two features, authentication (can be retrofitted in, just haven't yet), and proxying.
Proxying will probably need a completely new …
> Move dialplan logic fully into Application, remove dialog router

- examples/back_to_back/client.py
- examples/back_to_back/registrar.py
- examples/back_to_back/server.py
- examples/back_to_back/util.py
Now should similarly handle reregistrations and unregistration events, on top of having better handling of subscriptions. Similar changes to #75.
> Rework back-to-back example to improve registration and use new APIs

- setup.py
We use async generators, so no 3.5 support - unless someone wants to spend the time to re-add it.
> Drop python 3.5 support

- README.rst
- aiosip/application.py
- aiosip/dialog.py
- aiosip/peers.py
- aiosip/transaction.py
- examples/back_to_back/client.py
- examples/back_to_back/util.py
- examples/call/client.py
- examples/call/server.py
- tests/test_sip_scenario.py
Closed #77 and creates a new one because I ended up taking a slightly different approach with deeper changes that I'm more happy with.
This PR starts by reworks the dialog API so it **must** be paired with an initial message. This lets me removes the private `_subscribe` and `_register` methods in favour of a new `refresh` and `close` API that sends the right follow up message with the right "Expires" header.
Then I implement some basic INVITE dialog support. This requires its own dialog class implementation as it has its own call state information that needs to be tracked. INVITE really is a special case, and thus needs to be treated differently.
I think this lends itself a lot better to having a good REGISTER/SUBSCRIBE client API, but its also making it more and more clear that we need …
> Dialog rework with provisonal INVITE support

- aiosip/application.py
- aiosip/contact.py
- aiosip/dialog.py
- aiosip/peers.py
- aiosip/via.py
- tests/test_sip_proxy.py
This PR reworks how dialogs are tracked
Its actually wrong to try and first determine the remote address first, and then use that to work out which dialog a message belongs to - we don't have enough information to accurately make that determination.
All we have is sufficient information to determine which dialog and transaction a message belongs to.
Also in the case that a new inbound message arrives and needs to be run through the dialplan, the Contact header should be used instead of the socket's peername for figuring out where to return traffic.
So the current design needs to be broken and globally track all dialogs. Once we've established the dialog, we can get peer information. Dialogs are also now tracked by the set of the address contained in the To and From headers plus the …
> Redo dialog tracking

- aiosip/application.py
- aiosip/dialplan.py
- client.py
- examples/back_to_back/registrar.py
- examples/back_to_back/server.py
- examples/call/server.py
- examples/subscribe/client.py
- examples/subscribe/server.py
- tests/test_sip_proxy.py
- tests/test_sip_scenario.py
- tests/test_sip_server.py
Current dialplan was not correct and complicated. This rework
simplify it greatly and provide an easy way to do your own routing
I think it will be a nice place to put helpers for
authentifications.
No idea if that will provide any advantages over a flat mapping
of methods / middlewares
issue #78
> Dialplan custom

- aiosip/application.py
- aiosip/dialplan.py
Probably should just expose the message rather than parts of it, as one might need more information when deciding how to handle new traffic. For example, holes in the current API: access to the uri, to header, contact header, and potentially extension headers.
> Provide the original message to the dialplan

- Pipfile
- Pipfile.lock
- aiosip/application.py
- aiosip/dialog.py
- setup.py
- tests/conftest.py
- tests/test_sip_proxy.py
- tests/test_sip_scenario.py
- tests/test_sip_server.py
Imrpove application cleanup. This might need another pass
after #112 is merged
Issue #91 #92 
This also add a `timeout` argument to `dialog.request`
> Application cleanup

- Pipfile.lock
- aiosip/application.py
- aiosip/dialog.py
- aiosip/peers.py
- aiosip/utils.py
Some request can come without a `To` headers tag (after a 401 for
example). This should probably be done only for specific
status code.
Also catch `asyncio.CancelledError` of `dialog._closing`
> Temporarily add dialog with None tag to dialogs list

- aiosip/dialog.py
Necessary for aiosip under python 3.7
Sorry for my absence, had a really busy couple of months paired with some nasty hardware failures (my only laptop failed, had to replace it) - and I'm still not back up to 100%.
> __aiter__ must be a regular function

- aiosip/peers.py
I had to test something with multiple connection and quickly put that together. Since dialogs are not tracked by peer anymore it should work but I'm not sure there are no side effect.
I'll try to do some more tests on it soon.
> allow not reusing peer

- aiosip/auth.py
- tests/test_registration.py
This pull request cherry pick the sip auth fix from #125 since it is needed for our testing.
The unit test is added to verify the expected digest response.
> Registration fix

- aiosip/application.py
- aiosip/auth.py
- aiosip/contact.py
- aiosip/param.py
- aiosip/uri.py
- aiosip/via.py
In python3.7, importing MutableMapping directly from collections raise a deprecation warning:
```
>>> from collections import MutableMapping
__main__:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
Importing from collections.abc solve the warning :-)
P.S MutableMapping is part of collections.abc since 3.3
> import MutableMapping from collections.abc
